apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: a2odev-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
        livenessProbe:
          exec:
            command:
            - nginx
            - -t
          initialDelaySeconds: 60
          periodSeconds: 60

